session_name: jg-W6
start_directory: /home/sy/jg/03.c-language/me/w6_RBTree01/sy
suppress_history: false
windows:
  - window_name: document
    focus: true
    panes:
      - shell_command: vi -c 'cd ~/Documents/dev-wiki | VimwikiIndex'

  - window_name: code & build
    layout: e15c,240x66,0,0{186x66,0,0,114,53x66,187,0,115}
    start_directory: src
    panes:
      - shell_command:
          - tm.1_title 'editor'
          - vi .
        focus: true
      - shell_command:
          - tm.1_title 'build for debugging'
          - cmd: gcc -g -O0 <src>
            enter: false

  - window_name: debug
    panes:
      - shell_command:
          - tm.1_title 'debugger'
          - cmd: "gdb"
            enter: false

  - window_name: docker
    layout: main-vertical
    options:
      main-pane-width: 60%
    panes:
      - shell_command:
          - tm.1_title 'current container'
          - docker exec -it jg-c-w6 bash
          - make help
        focus: true
      - shell_command: vi config/Dockerfile
      - shell_command:
          - tm.1_title 'build image'
          - cmd: docker build -t jg-c-w6 config/
            enter: false
      - shell_command:
          - tm.1_title 'run daemon container'
          - cmd: docker run -d --name jg-c-w6 -v "$(git-root)/sy:/workspace" --network=host jg-c-w6
            enter: false
      - shell_command: lazydocker

  - window_name: config
    layout: even-horizontal
    panes:
      - shell_command: vi config/tmuxp.yaml
